import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowDownToLine, ArrowRight, Camera, Mail, Newspaper, Phone } from 'lucide-react';
import { CopyTextButton } from '@/components/copy-text-button';
import { PageShell } from '@/components/site-chrome';

export const metadata: Metadata = {
  title: 'Za medije i partnere | Vespera namještaj',
  description: 'Osnovni opisi Vespere, logotipi i kontakt za novinarske upite, najave i poslovne suradnje.',
  alternates: { canonical: '/za-medije' },
};

const oneSentence = 'Vespera je salon namještaja u Karlovcu koji povezuje osobno savjetovanje, aktualnu ponudu namještaja te planiranje kuhinja i namještaja po mjeri.';

const shortDescription = 'Vespera namještaj je lokalni salon u Karlovcu. Kupcima pomaže odabrati namještaj prema prostoru, potrebama i budžetu, a poseban dio ponude čine kuhinje i druga rješenja po mjeri. Budući da se dio asortimana naručuje u ograničenim količinama, dostupnost pojedinog modela, boje i izvedbe provjerava se sa salonom.';

const longDescription = 'Vespera namještaj je salon u Karlovcu usmjeren na osobno savjetovanje, opremanje doma i planiranje namještaja prema stvarnom prostoru. Ponuda obuhvaća namještaj za dnevni boravak, spavaću sobu, blagovaonicu, predsoblje i druge dijelove doma, uz kuhinje i odabrana rješenja po mjeri. Kupci proizvode mogu pogledati i isprobati u salonu, usporediti materijale te prije narudžbe provjeriti dimenzije, dostupnost, rok, dostavu i mogućnosti plaćanja. Dio namještaja naručuje se u ograničenim količinama, pa se isti model ne mora ponovno pojaviti nakon prodaje zalihe. Zbog toga Vespera na webu jasno odvaja proizvode dostupne odmah od modela koji se naručuju. Kod kuhinja i namještaja po mjeri proces počinje razgovorom o prostoru, navikama i budžetu, a nastavlja se izmjerom, prijedlogom rasporeda i pisanom ponudom. Cilj je pomoći kupcu donijeti sigurniju odluku bez nepotrebnog tehničkog žargona.';

const mediaTopics = [
  { title: 'Kako kupovati kada se ponuda stalno mijenja?', text: 'Dostupnost, ograničene količine i zašto je provjera prije dolaska važna.' },
  { title: 'Kuhinja po mjeri počinje navikama', text: 'Kako prostor, način kuhanja, pristupačnost i budžet utječu na dobar raspored.' },
  { title: 'Namještaj koji je lakše koristiti', text: 'Visina sjedišta, prolazi, održavanje i druge odluke koje podižu svakodnevnu udobnost.' },
  { title: 'Vrijednost fizičkog salona', text: 'Zašto su isprobavanje, uzorci i razgovor i dalje važni kod većih odluka za dom.' },
];

export default function MediaPage() {
  return <PageShell><main>
    <section className="media-hero"><div className="container media-hero-grid"><div><nav className="breadcrumbs dark-breadcrumbs" aria-label="Putanja"><Link href="/">Početna</Link><span aria-hidden="true">/</span><span>Za medije</span></nav><p className="eyebrow">Za medije i partnere</p><h1>Priča, tekstovi i materijali. Na jednom mjestu.</h1><p className="lead">Osnovne informacije o Vesperi pripremljene su za članke, najave i poslovne suradnje. Tekstove možete skratiti i urednički prilagoditi.</p><div className="hero-actions"><a className="button button-accent" href="#tekstovi">Tekstovi za kopiranje <ArrowRight aria-hidden="true" /></a><a className="button button-dark-outline" href="#materijali">Logotipi i materijali <ArrowDownToLine aria-hidden="true" /></a></div></div><div className="media-hero-mark" aria-label="Vespera namještaj"><Image src="/brand/vespera-logo-yellow.svg" alt="Vespera namještaj" width={560} height={168} /><p>Salon namještaja i kuhinje po mjeri u Karlovcu.</p></div></div></section>

    <nav className="media-index container" aria-label="Sadržaj stranice"><a href="#tekstovi"><span>01</span> Tekstovi</a><a href="#materijali"><span>02</span> Logotipi</a><a href="#teme"><span>03</span> Teme</a><a href="#kontakt"><span>04</span> Kontakt</a></nav>

    <section className="section container" id="tekstovi"><div className="section-head"><div><p className="eyebrow">Odaberite duljinu</p><h2>Spremno za kopiranje.</h2></div><p>Neutralni tekstovi bez reklamnih superlativa. Prije objave podataka o ponudi, cijenama ili rokovima provjerite aktualno stanje sa salonom.</p></div><div className="media-copy-grid"><article><div className="media-card-head"><span>Jedna rečenica</span><small>{oneSentence.split(' ').length} riječi</small></div><p>{oneSentence}</p><CopyTextButton text={oneSentence} /></article><article><div className="media-card-head"><span>Kratki opis</span><small>{shortDescription.split(' ').length} riječi</small></div><p>{shortDescription}</p><CopyTextButton text={shortDescription} /></article><article className="media-copy-long"><div className="media-card-head"><span>Opis za članak</span><small>{longDescription.split(' ').length} riječi</small></div><p>{longDescription}</p><CopyTextButton text={longDescription} /></article></div><a className="text-link media-download-text" href="/media/vespera-opisi-za-medije.txt" download><ArrowDownToLine aria-hidden="true" /> Preuzmite sve tekstove u TXT datoteci</a></section>

    <section className="media-materials" id="materijali"><div className="container"><div className="section-head"><div><p className="eyebrow">Materijali za preuzimanje</p><h2>Vespera logotipi.</h2></div><p>Preuzmite izvornu datoteku, ne sliku pregleda. Nemojte mijenjati boje, rastezati logo ili odvajati njegove dijelove.</p></div><div className="media-assets-grid"><article><div className="media-asset-preview media-asset-square"><Image src="/brand/vespera-logo-primary.svg" alt="Vespera kvadratni logo" width={512} height={512} /></div><h3>Kvadratni logo</h3><p>Izvorna žuto-crna kompozicija za profilne fotografije, plakate i kvadratne formate.</p><a className="text-link" href="/brand/vespera-logo-primary.svg" download>Preuzmite SVG <ArrowDownToLine aria-hidden="true" /></a></article><article><div className="media-asset-preview media-asset-light"><Image src="/brand/vespera-logo-horizontal.svg" alt="Vespera horizontalni logo" width={560} height={168} /></div><h3>Horizontalni logo</h3><p>Preporučen za zaglavlja, potpise i svijetle podloge.</p><a className="text-link" href="/brand/vespera-logo-horizontal.svg" download>Preuzmite SVG <ArrowDownToLine aria-hidden="true" /></a></article><article><div className="media-asset-preview media-asset-dark"><Image src="/brand/vespera-logo-yellow.svg" alt="Vespera žuti logo za tamnu podlogu" width={560} height={168} /></div><h3>Logo za tamnu podlogu</h3><p>Žuta varijanta za tamne površine i fotografije dovoljnog kontrasta.</p><a className="text-link" href="/brand/vespera-logo-yellow.svg" download>Preuzmite SVG <ArrowDownToLine aria-hidden="true" /></a></article><article><div className="media-asset-preview media-asset-yellow"><Image src="/brand/vespera-logo-black.svg" alt="Vespera crni logo" width={560} height={168} /></div><h3>Crni logo</h3><p>Jednobojna varijanta za žute i vrlo svijetle podloge.</p><a className="text-link" href="/brand/vespera-logo-black.svg" download>Preuzmite SVG <ArrowDownToLine aria-hidden="true" /></a></article></div><div className="media-vector-download"><ArrowDownToLine aria-hidden="true" /><div><h3>Svi logotipi u jednom paketu</h3><p>Vektorske SVG datoteke za tisak i digitalnu upotrebu.</p></div><a className="button button-accent" href="/brand/vespera-logo-vektori.zip" download>Preuzmite ZIP paket</a></div><p className="media-usage-note"><strong>Korištenje materijala</strong> Logotipe možete koristiti uz novinarske priloge i dogovorene najave o Vesperi. Za oglašavanje, partnerske kampanje i druge komercijalne namjene zatražite odobrenje. Fotografije proizvoda mogu imati zasebna prava proizvođača, zato ih nemojte preuzimati bez prethodne potvrde.</p></div></section>

    <section className="section container" id="teme"><div className="section-head"><div><p className="eyebrow">Prijedlozi za razgovor</p><h2>Teme koje možemo objasniti iz prakse.</h2></div><p>Vespera može ponuditi perspektivu lokalnog salona, procesa odabira i planiranja namještaja za stvarne domove.</p></div><div className="media-topics">{mediaTopics.map((topic, index) => <article key={topic.title}><span>{String(index + 1).padStart(2, '0')}</span><Newspaper aria-hidden="true" /><div><h3>{topic.title}</h3><p>{topic.text}</p></div></article>)}</div></section>

    <section className="media-contact" id="kontakt"><div className="container media-contact-grid"><div><p className="eyebrow">Kontakt za medije i suradnje</p><h2>Trebate izjavu, fotografiju ili dodatne podatke?</h2><p>U poruci navedite medij ili organizaciju, temu koju pripremate, potreban format i rok. Dostupnost sugovornika potvrđuje se naknadno.</p></div><div className="media-contact-actions"><a href="mailto:namjestaj@vespera.hr?subject=Upit%20za%20medije%20ili%20suradnju"><Mail aria-hidden="true" /><span><small>E-mail</small><strong>namjestaj@vespera.hr</strong></span></a><a href="tel:+38547645535"><Phone aria-hidden="true" /><span><small>Telefon salona</small><strong>047 645 535</strong></span></a><Link href="/novosti"><Camera aria-hidden="true" /><span><small>Aktualne objave</small><strong>Pogledajte novosti</strong></span></Link></div></div></section>
  </main></PageShell>;
}
