'use client';

import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft, ArrowRight, Camera, Check, CheckCircle2, Clipboard, Grid2X2, ImagePlus, MapPin, Phone, Ruler, Send } from 'lucide-react';
import { PageShell } from '@/components/site-chrome';

const layouts = ['Ravna', 'L-kuhinja', 'U-kuhinja', 'Otok ili poluotok', 'Još ne znam'];
const budgets = ['Do 5.000 €', 'Od 5.000 do 10.000 €', 'Od 10.000 do 15.000 €', 'Više od 15.000 €', 'Trebam procjenu'];

export default function KuhinjePage() {
  const [layout, setLayout] = useState('');
  const [budget, setBudget] = useState('');
  const [summary, setSummary] = useState<{name:string;phone:string;email:string;date:string;time:string;message:string}|null>(null);
  const [copyStatus, setCopyStatus] = useState('');
  function submit(event: {preventDefault:()=>void;currentTarget:HTMLFormElement}) { event.preventDefault(); const data = new FormData(event.currentTarget); const value = (name:string) => { const field = data.get(name); return typeof field === 'string' ? field : ''; }; setSummary({name:value('name'),phone:value('phone'),email:value('email'),date:value('date'),time:value('time'),message:value('message')}); }
  async function copySummary(){ if(!summary)return; const text=`Priprema projekta kuhinje\nIme: ${summary.name}\nTelefon: ${summary.phone}\nE-mail: ${summary.email || 'Nije unesen'}\nŽeljeni datum: ${summary.date}\nVrijeme: ${summary.time}\nRaspored: ${layout}\nBudžet: ${budget}\nNapomena: ${summary.message || 'Nije unesena'}`; try { await navigator.clipboard.writeText(text); setCopyStatus('Sažetak je kopiran.'); } catch { setCopyStatus('Kopiranje nije uspjelo. Podatke možete pročitati sa zaslona.'); } }

  return <PageShell><main>
    <section className="kitchen-hero"><div className="container kitchen-hero-grid"><div><nav className="breadcrumbs dark-breadcrumbs" aria-label="Putanja"><Link href="/">Početna</Link><span aria-hidden="true">/</span><span>Kuhinje po mjeri</span></nav><p className="eyebrow">Besplatna izmjera i 3D planiranje</p><h1>Vaša kuhinja počinje dobrim razgovorom.</h1><p className="lead">Planiramo prema prostoru, navikama i budžetu. Okvirni rok je oko 30 dana, a početak njegova računanja i konačan datum navode se na pisanoj ponudi.</p><div className="kitchen-price-anchor"><span>Kuhinje po mjeri</span><strong>Cijena prema izvedbi</strong><small>Prijedlog se prilagođava prostoru i budžetu. Konačna cijena ovisi o dimenzijama, materijalima, okovima, uređajima i dogovorenim uslugama.</small></div><div className="hero-actions"><a className="button button-accent" href="#projekt">Pripremite zahtjev za planiranje <ArrowRight aria-hidden="true" /></a><a className="button button-dark-outline" href="tel:+38547645535"><Phone aria-hidden="true" /> 047 645 535</a></div></div><div className="kitchen-hero-image"><Image src="https://vespera.hr/wp-content/uploads/2026/06/csm_inspiration_stage_laser_412_3bd5d5fd87.jpg" alt="Suvremena kuhinja s radnim otokom" width={1680} height={800} sizes="(max-width: 920px) 100vw, 45vw" priority /><span>Izmjera i 3D prijedlog bez naknade</span></div></div></section>

    <section className="container kitchen-boundaries" aria-labelledby="kitchen-boundaries-title"><div className="kitchen-boundaries-head"><p className="eyebrow">Što obećanje znači</p><h2 id="kitchen-boundaries-title">Jasno prije prvog koraka.</h2></div><div className="kitchen-boundaries-grid"><article><span>01</span><h3>Besplatna izmjera</h3><p>Izmjera služi pripremi Vesperina prijedloga. Područje dolaska, termin i uvjete usluge salon potvrđuje prije izlaska na teren.</p></article><article><span>02</span><h3>3D prijedlog</h3><p>Pomaže razumjeti raspored i izgled. Nije konačan izvedbeni nacrt niti potvrda da su sve instalacije i tehnički uvjeti provjereni.</p></article><article><span>03</span><h3>Okvirni rok</h3><p>Oko 30 dana je orijentacija, ne zajamčeni datum. Točan rok ovisi o potvrđenoj izvedbi, materijalima i dobavljivosti.</p></article><article><span>04</span><h3>Dostava i montaža</h3><p>Opseg i cijena navode se na ponudi. Priključivanje uređaja, demontaža, odvoz i priprema zidova ne podrazumijevaju se bez izričite potvrde.</p></article></div></section>

    <section className="section container"><div className="section-head"><div><p className="eyebrow">Kako radimo</p><h2>Od prve ideje do gotove kuhinje.</h2></div><p>Prije narudžbe znate što se prilagođava, što ulazi u cijenu i tko vodi sljedeći korak.</p></div><ol className="kitchen-steps"><li><span>01</span><div><h3>Prvi razgovor</h3><p>Prolazimo vaše navike, želje, uređaje i okvirni budžet.</p></div></li><li><span>02</span><div><h3>Izmjera prostora</h3><p>Provjeravamo zidove, priključke, prozore i prolaze.</p></div></li><li><span>03</span><div><h3>3D prijedlog</h3><p>Raspored i izgled vidite prije konačne odluke.</p></div></li><li><span>04</span><div><h3>Ponuda i potvrda</h3><p>Dobivate specifikaciju materijala, usluga, cijene i roka.</p></div></li><li><span>05</span><div><h3>Dostava i montaža</h3><p>Dogovaramo dolazak i stručnu montažu u vašem prostoru.</p></div></li></ol></section>

    <section className="kitchen-prep" id="priprema"><div className="container"><div className="section-head"><div><p className="eyebrow">Prije prvog razgovora</p><h2>Ne trebate gotov nacrt.</h2></div><p>Dovoljno je donijeti osnovne informacije. Točne mjere i konačnu izvedbu Vespera provjerava prije narudžbe.</p></div><div className="kitchen-prep-grid"><article><Ruler aria-hidden="true" /><span>01</span><h3>Izmjerite prostor</h3><ul><li>Duljinu svakog zida i visinu prostorije</li><li>Širinu i visinu vrata i prozora</li><li>Visinu prozorske klupčice</li><li>Udaljenost do kutova i drugih prepreka</li></ul></article><article><Camera aria-hidden="true" /><span>02</span><h3>Fotografirajte detalje</h3><ul><li>Svaki zid iz što šireg kuta</li><li>Vodu, odvod, utičnice i ventilaciju</li><li>Radijator, bojler, cijevi i kosine</li><li>Ulaz i prolaz do prostorije</li></ul></article><article><Clipboard aria-hidden="true" /><span>03</span><h3>Zapišite što vam treba</h3><ul><li>Uređaje koje zadržavate ili kupujete</li><li>Što vam sada nedostaje ili smeta</li><li>Boje i stilove koji vam se sviđaju</li><li>Okvirni budžet i željeni termin</li></ul></article></div><div className="kitchen-prep-note"><CheckCircle2 aria-hidden="true" /><p><strong>Približne mjere dovoljne su za prvi razgovor.</strong> Nemojte naručivati elemente prema vlastitim mjerama. Konačne dimenzije treba potvrditi stručnom izmjerom.</p><Link className="text-link" href="/blog/priprema-kuhinje-po-mjeri">Otvorite detaljan vodič <ArrowRight aria-hidden="true" /></Link></div></div></section>

    <section className="section container kitchen-appointment" aria-labelledby="appointment-title"><div><p className="eyebrow">Razgovor u salonu</p><h2 id="appointment-title">Što se događa na terminu?</h2><p>Ne očekujemo da znate stručne nazive. Savjetnik pitanja pretvara u konkretan raspored i pomaže usporediti opcije koje odgovaraju prostoru i budžetu.</p></div><ol><li><span>01</span><div><h3>Razgovaramo o svakodnevici</h3><p>Tko koristi kuhinju, kako kuhate, što treba biti nadohvat ruke i što želite promijeniti.</p></div></li><li><span>02</span><div><h3>Uspoređujemo materijale</h3><p>Fronte, radne ploče, ručkice i okove najbolje je vidjeti i dodirnuti uživo.</p></div></li><li><span>03</span><div><h3>Slažemo početni raspored</h3><p>Provjeravamo radne zone, prolaze, visine i položaj uređaja.</p></div></li><li><span>04</span><div><h3>Dogovaramo sljedeći korak</h3><p>Dobivate jasan popis otvorenih odluka i dogovor za izmjeru, doradu ili ponudu.</p></div></li></ol></section>

    <section className="visualizer-section"><div className="container visualizer-grid"><div><p className="eyebrow">Pripremite prostor prije termina</p><h2>Složite prvi nacrt svoje kuhinje.</h2><p>Unesite dimenzije, označite vrata, prozore i priključke te rasporedite osnovne kuhinjske elemente. Dobit ćete jasan sažetak koji možete ponijeti ili poslati savjetniku.</p><p className="prototype-note">Nacrt je orijentacijski. Konačne mjere, materijale, cijenu i 3D prijedlog potvrđuje Vespera.</p></div><div className="visualizer-tool"><Grid2X2 size={42} aria-hidden="true" /><div><strong>Vespera Planer Lite</strong><p>Četiri jasna koraka, bez stručnog programa i bez registracije.</p></div><ul className="planner-feature-list"><li>Mjere prostorije</li><li>Vrata, prozori i priključci</li><li>Elementi u mjerilu</li><li>PDF i sažetak za savjetnika</li></ul><Link className="button button-accent" href="/vizualizator">Otvorite planer kuhinje</Link></div></div></section>

    <section className="project-section" id="projekt"><div className="container project-grid"><div className="project-copy"><p className="eyebrow">Digitalna priprema termina</p><h2>Pošaljite početne informacije.</h2><p>Ne morate imati savršene mjere. Dovoljna je približna skica, nekoliko fotografija i opis onoga što vam je važno.</p><div className="project-benefits"><p><Ruler aria-hidden="true" /><span><strong>Manje nagađanja</strong> prije prvog sastanka</span></p><p><ImagePlus aria-hidden="true" /><span><strong>Fotografije i skica</strong> daju kontekst prostoru</span></p><p><MapPin aria-hidden="true" /><span><strong>Termin u salonu</strong> koristi se za konkretne odluke</span></p></div><p className="prototype-note">Ovo je funkcionalni prototip. Uneseni podaci se ne šalju Vesperi.</p></div>
      <form className="project-form" onSubmit={submit} aria-label="Priprema projekta kuhinje">
        {summary ? <div className="success-state" aria-live="polite"><Check size={46} aria-hidden="true" /><h3>Zahtjev za termin je pripremljen.</h3><p>U stvarnoj verziji Vespera bi potvrdila termin telefonom ili e-mailom. U ovom prototipu podaci se ne šalju.</p><dl className="project-summary"><div><dt>Ime</dt><dd>{summary.name}</dd></div><div><dt>Telefon</dt><dd>{summary.phone}</dd></div>{summary.email && <div><dt>E-mail</dt><dd>{summary.email}</dd></div>}<div><dt>Željeni termin</dt><dd>{summary.date}, {summary.time}</dd></div><div><dt>Raspored</dt><dd>{layout}</dd></div><div><dt>Budžet</dt><dd>{budget}</dd></div>{summary.message && <div><dt>Napomena</dt><dd>{summary.message}</dd></div>}</dl><div className="summary-actions"><button type="button" className="button button-accent" onClick={copySummary}><Clipboard aria-hidden="true" /> Kopirajte zahtjev</button><a className="button" href="tel:+38547645535"><Phone aria-hidden="true" /> Nazovite salon</a><button type="button" className="button button-ghost" onClick={() => {setSummary(null);setCopyStatus('');}}>Uredite podatke</button></div>{copyStatus && <output className="copy-status">{copyStatus}</output>}</div> : <>
          <fieldset><legend>1. Kakav raspored razmatrate?</legend><div className="choice-grid">{layouts.map((item, index) => <label key={item} className={layout === item ? 'choice selected' : 'choice'}><input type="radio" name="layout" value={item} checked={layout === item} onChange={() => setLayout(item)} required={index === 0} /><span>{item}</span></label>)}</div></fieldset>
          <fieldset><legend>2. Koji je okvirni budžet?</legend><div className="choice-grid">{budgets.map((item, index) => <label key={item} className={budget === item ? 'choice selected' : 'choice'}><input type="radio" name="budget" value={item} checked={budget === item} onChange={() => setBudget(item)} required={index === 0} /><span>{item}</span></label>)}</div></fieldset>
          <fieldset><legend>3. Kada vam odgovara razgovor u salonu?</legend><div className="field-grid"><label><span>Željeni datum</span><input type="date" name="date" required /></label><label><span>Dio dana</span><select name="time" defaultValue="" required><option value="" disabled>Odaberite vrijeme</option><option>Prijepodne, od 9 do 12 sati</option><option>Poslijepodne, od 12 do 16 sati</option><option>Nazovite me radi dogovora</option></select></label></div><p className="field-help">Termin vrijedi tek nakon potvrde Vespere.</p></fieldset>
          <div className="field-grid"><label><span>Ime i prezime</span><input type="text" name="name" autoComplete="name" required /></label><label><span>Telefon</span><input type="tel" name="phone" autoComplete="tel" required /></label></div>
          <label><span>E-mail, nije obavezno</span><input type="email" name="email" autoComplete="email" /></label>
          <label><span>Što želite promijeniti u prostoru?</span><textarea name="message" rows={4} placeholder="Npr. treba mi više radne plohe i lakši pristup posuđu." /></label>
          <label className="file-field"><ImagePlus aria-hidden="true" /><span><strong>Dodajte fotografije ili skicu</strong><small>JPG, PNG ili PDF u stvarnoj verziji</small></span><input type="file" multiple accept="image/*,.pdf" /></label>
          <button className="button button-accent form-submit" type="submit"><Send aria-hidden="true" /> Pripremite zahtjev za termin</button>
        </>}
      </form>
    </div></section>

    <section className="section container"><div className="kitchen-clarity"><div><p className="eyebrow">Bez nejasnih obećanja</p><h2>Što znači “po mjeri”?</h2><p>Mogućnosti ovise o odabranom kuhinjskom sustavu. Na ponudi treba jasno pisati koji su elementi standardni, što se konfigurira i gdje je moguća posebna prilagodba.</p></div><div className="clarity-list"><p><strong>Moduli</strong><span>Dostupne širine i rasporedi elemenata</span></p><p><strong>Materijali</strong><span>Fronte, korpusi, radne ploče i okovi</span></p><p><strong>Prilagodbe</strong><span>Završne stranice, ispune, visine i radna ploča</span></p><p><strong>Usluga</strong><span>Mjerenje, planiranje, dostava i montaža</span></p></div></div></section>

    <section className="kitchen-deliverables"><div className="container"><div className="section-head"><div><p className="eyebrow">Prije nego kažete da</p><h2>Što trebate dobiti u ponudi?</h2></div><p>Dobra ponuda omogućuje da razumijete cijenu i usporedite rješenja bez skrivenih pretpostavki.</p></div><div className="deliverables-grid"><div><h3>Jasno navedeno</h3><ul><li>Raspored i dimenzije elemenata</li><li>Materijali fronti, korpusa i radne ploče</li><li>Vrsta okova i unutarnje opreme</li><li>Uređaji i dodaci koji su uključeni</li><li>Dostava, montaža i predviđeni rok</li></ul></div><div><h3>Posebno provjerite</h3><ul><li>Priključivanje vode, struje i plina</li><li>Demontažu i odvoz stare kuhinje</li><li>Izreze, završne letvice i zidne obloge</li><li>Odvoz ambalaže nakon montaže</li><li>Jamstva i postupak reklamacije</li></ul></div></div><p className="deliverables-note">Konačan sadržaj usluge ovisi o dogovoru s Vesperom. Ovaj popis pomaže da prije narudžbe ništa važno ne ostane neizgovoreno.</p></div></section>

    <section className="section container kitchen-faq" aria-labelledby="kitchen-faq-title"><div className="faq-grid"><div><p className="eyebrow">Najčešća pitanja</p><h2 id="kitchen-faq-title">Kratki odgovori prije planiranja.</h2><p>Ako odgovor ovisi o prostoru ili odabranom programu, to ćemo jasno reći i provjeriti prije narudžbe.</p><a className="button button-accent" href="tel:+38547645535"><Phone aria-hidden="true" /> Nazovite 047 645 535</a></div><div><details><summary>Moram li imati točne mjere prije dolaska?</summary><p>Ne. Za prvi razgovor dovoljne su približne mjere, fotografije i jednostavna skica. Konačne dimenzije treba provjeriti stručnom izmjerom.</p></details><details><summary>Koliko traje planiranje kuhinje?</summary><p>Prvi razgovor treba ostaviti dovoljno vremena za potrebe, raspored i materijale. Točno trajanje i broj dorada ovise o složenosti prostora i odluka.</p></details><details><summary>Je li 3D prijedlog isto što i konačan izvedbeni nacrt?</summary><p>Nije. 3D prikaz pomaže razumjeti raspored i izgled. Konačna izvedba potvrđuje se nakon provjere mjera, priključaka, elemenata i materijala.</p></details><details><summary>Jesu li uređaji, dostava i montaža uključeni u cijenu?</summary><p>To mora biti izričito navedeno u ponudi. Prije narudžbe provjerite svaku uslugu i uređaj zasebno.</p></details><details><summary>Mogu li zadržati postojeće uređaje?</summary><p>U pravilu se mogu planirati postojeći uređaji ako su prikladni za novi raspored. Ponesite njihove točne dimenzije, oznaku modela i fotografije priključaka.</p></details><details><summary>Može li kuhinja biti prilagođena lakšem korištenju?</summary><p>Da. Visina radne plohe, položaj pećnice, izvlačne ladice, rasvjeta i slobodan prostor mogu se planirati prema načinu korištenja i pokretljivosti.</p></details><details><summary>Kako mogu kontrolirati budžet?</summary><p>Recite okvirni iznos na početku. Savjetnik tada može usporediti materijale, okove i rasporede te pokazati gdje se isplati uložiti, a gdje pojednostaviti.</p></details><details><summary>Kada dobivam konačnu cijenu i rok?</summary><p>Nakon potvrđenih mjera, odabranih materijala, uređaja i usluga. Cijena i rok trebaju biti navedeni u ponudi prije narudžbe.</p></details></div></div><Link className="text-link back-link" href="/"><ArrowLeft aria-hidden="true" /> Natrag na početnu</Link></section>
  </main></PageShell>;
}
