'use client';

import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft, ArrowRight, Check, Clipboard, Eye, ImagePlus, MapPin, Phone, Ruler, Send } from 'lucide-react';
import { PageShell } from '@/components/site-chrome';

const layouts = ['Ravna', 'L-kuhinja', 'U-kuhinja', 'Otok ili poluotok', 'Još ne znam'];
const budgets = ['Do 5.000 €', 'Od 5.000 do 10.000 €', 'Od 10.000 do 15.000 €', 'Više od 15.000 €', 'Trebam procjenu'];

export default function KuhinjePage() {
  const [layout, setLayout] = useState('');
  const [budget, setBudget] = useState('');
  const [summary, setSummary] = useState<{name:string;phone:string;email:string;date:string;time:string;message:string}|null>(null);
  const [copyStatus, setCopyStatus] = useState('');
  const [visualFile, setVisualFile] = useState('');
  const [visualStyle, setVisualStyle] = useState('Topla bijela i drvo');
  function submit(event: {preventDefault:()=>void;currentTarget:HTMLFormElement}) { event.preventDefault(); const data = new FormData(event.currentTarget); const value = (name:string) => { const field = data.get(name); return typeof field === 'string' ? field : ''; }; setSummary({name:value('name'),phone:value('phone'),email:value('email'),date:value('date'),time:value('time'),message:value('message')}); }
  async function copySummary(){ if(!summary)return; const text=`Priprema projekta kuhinje\nIme: ${summary.name}\nTelefon: ${summary.phone}\nE-mail: ${summary.email || 'Nije unesen'}\nŽeljeni datum: ${summary.date}\nVrijeme: ${summary.time}\nRaspored: ${layout}\nBudžet: ${budget}\nNapomena: ${summary.message || 'Nije unesena'}`; try { await navigator.clipboard.writeText(text); setCopyStatus('Sažetak je kopiran.'); } catch { setCopyStatus('Kopiranje nije uspjelo. Podatke možete pročitati sa zaslona.'); } }

  return <PageShell><main>
    <section className="kitchen-hero"><div className="container kitchen-hero-grid"><div><nav className="breadcrumbs dark-breadcrumbs" aria-label="Putanja"><Link href="/">Početna</Link><span aria-hidden="true">/</span><span>Kuhinje po mjeri</span></nav><p className="eyebrow">Besplatna izmjera i 3D planiranje</p><h1>Vaša kuhinja počinje dobrim razgovorom.</h1><p className="lead">Planiramo prema prostoru, navikama i budžetu. Okvirni rok isporuke je oko 30 dana, a konačan rok potvrđujemo prije narudžbe.</p><div className="kitchen-price-anchor"><span>Kuhinje po mjeri</span><strong>od 1.000 €</strong><small>Orijentacijska početna cijena. Konačna cijena ovisi o dimenzijama, materijalima, uređajima i montaži.</small></div><div className="hero-actions"><a className="button button-accent" href="#projekt">Rezervirajte besplatno planiranje <ArrowRight aria-hidden="true" /></a><a className="button button-dark-outline" href="tel:+38547645535"><Phone aria-hidden="true" /> 047 645 535</a></div></div><div className="kitchen-hero-image"><Image src="https://vespera.hr/wp-content/uploads/2026/06/csm_inspiration_stage_laser_412_3bd5d5fd87.jpg" alt="Suvremena kuhinja s radnim otokom" width={1680} height={800} sizes="(max-width: 920px) 100vw, 45vw" priority /><span>Izmjera i 3D prijedlog bez naknade</span></div></div></section>

    <section className="section container"><div className="section-head"><div><p className="eyebrow">Kako radimo</p><h2>Jedan proces. Jasni koraci.</h2></div><p>Prije narudžbe znate što se prilagođava, što ulazi u cijenu i tko vodi sljedeći korak.</p></div><ol className="kitchen-steps"><li><span>01</span><div><h3>Besplatna izmjera</h3><p>Provjeravamo zidove, priključke, prozore i prolaze.</p></div></li><li><span>02</span><div><h3>Razgovor i budžet</h3><p>Navike, stil, uređaji i iznos koji želite uložiti.</p></div></li><li><span>03</span><div><h3>Besplatan 3D prijedlog</h3><p>Raspored vidite prije konačne odluke.</p></div></li><li><span>04</span><div><h3>Jasna ponuda</h3><p>Materijali, okovi, usluge, cijena i potvrđeni rok.</p></div></li><li><span>05</span><div><h3>Dostava i montaža</h3><p>Stručna montaža i uredan prostor nakon završetka.</p></div></li></ol></section>

    <section className="visualizer-section"><div className="container visualizer-grid"><div><p className="eyebrow">Pripremite ideju prije termina</p><h2>Kako bi nova kuhinja mogla izgledati u vašem prostoru?</h2><p>Dodajte fotografiju prostora i odaberite smjer koji vam se sviđa. Ovaj alat priprema kratak vizualni zahtjev za savjetnika. Konačni 3D prijedlog izrađuje Vespera nakon izmjere.</p><p className="prototype-note">Fotografija ostaje samo na vašem uređaju i ne šalje se u ovom prototipu.</p></div><div className="visualizer-tool"><label className="visual-upload"><ImagePlus aria-hidden="true" /><span><strong>{visualFile || 'Dodajte fotografiju prostorije'}</strong><small>JPG ili PNG</small></span><input type="file" accept="image/jpeg,image/png" onChange={(event) => setVisualFile(event.target.files?.[0]?.name || '')} /></label><label><span>Stil koji želite istražiti</span><select value={visualStyle} onChange={(event) => setVisualStyle(event.target.value)}><option>Topla bijela i drvo</option><option>Svijetla i minimalistička</option><option>Tamna i elegantna</option><option>Klasična i topla</option><option>Još ne znam</option></select></label><div className="visual-summary" aria-live="polite"><Eye aria-hidden="true" /><div><strong>Priprema za savjetnika</strong><p>{visualFile ? `Fotografija: ${visualFile}. ` : 'Fotografija još nije dodana. '}Smjer: {visualStyle}.</p></div></div><Link className="button button-accent" href="/vizualizator">Otvorite puni vizualni planer</Link></div></div></section>

    <section className="project-section" id="projekt"><div className="container project-grid"><div className="project-copy"><p className="eyebrow">Digitalna priprema termina</p><h2>Pošaljite početne informacije.</h2><p>Ne morate imati savršene mjere. Dovoljna je približna skica, nekoliko fotografija i opis onoga što vam je važno.</p><div className="project-benefits"><p><Ruler aria-hidden="true" /><span><strong>Manje nagađanja</strong> prije prvog sastanka</span></p><p><ImagePlus aria-hidden="true" /><span><strong>Fotografije i skica</strong> daju kontekst prostoru</span></p><p><MapPin aria-hidden="true" /><span><strong>Termin u salonu</strong> koristi se za konkretne odluke</span></p></div><p className="prototype-note">Ovo je funkcionalni prototip. Uneseni podaci se ne šalju Vesperi.</p></div>
      <form className="project-form" onSubmit={submit} aria-label="Priprema projekta kuhinje">
        {summary ? <div className="success-state" aria-live="polite"><Check size={46} aria-hidden="true" /><h3>Zahtjev za termin je pripremljen.</h3><p>U stvarnoj verziji Vespera bi potvrdila termin telefonom ili e-mailom. U ovom prototipu podaci se ne šalju.</p><dl className="project-summary"><div><dt>Ime</dt><dd>{summary.name}</dd></div><div><dt>Telefon</dt><dd>{summary.phone}</dd></div>{summary.email && <div><dt>E-mail</dt><dd>{summary.email}</dd></div>}<div><dt>Željeni termin</dt><dd>{summary.date}, {summary.time}</dd></div><div><dt>Raspored</dt><dd>{layout}</dd></div><div><dt>Budžet</dt><dd>{budget}</dd></div>{summary.message && <div><dt>Napomena</dt><dd>{summary.message}</dd></div>}</dl><div className="summary-actions"><button type="button" className="button button-accent" onClick={copySummary}><Clipboard aria-hidden="true" /> Kopirajte zahtjev</button><a className="button" href="tel:+38547645535"><Phone aria-hidden="true" /> Nazovite salon</a><button type="button" className="button button-ghost" onClick={() => {setSummary(null);setCopyStatus('');}}>Uredite podatke</button></div>{copyStatus && <output className="copy-status">{copyStatus}</output>}</div> : <>
          <fieldset><legend>1. Kakav raspored razmatrate?</legend><div className="choice-grid">{layouts.map((item, index) => <label key={item} className={layout === item ? 'choice selected' : 'choice'}><input type="radio" name="layout" value={item} checked={layout === item} onChange={() => setLayout(item)} required={index === 0} /><span>{item}</span></label>)}</div></fieldset>
          <fieldset><legend>2. Koji je okvirni budžet?</legend><div className="choice-grid">{budgets.map((item, index) => <label key={item} className={budget === item ? 'choice selected' : 'choice'}><input type="radio" name="budget" value={item} checked={budget === item} onChange={() => setBudget(item)} required={index === 0} /><span>{item}</span></label>)}</div></fieldset>
          <fieldset><legend>3. Kada vam odgovara razgovor u salonu?</legend><div className="field-grid"><label><span>Željeni datum</span><input type="date" name="date" required /></label><label><span>Dio dana</span><select name="time" defaultValue="" required><option value="" disabled>Odaberite vrijeme</option><option>Prijepodne, od 9 do 12 sati</option><option>Poslijepodne, od 12 do 16 sati</option><option>Nazovite me radi dogovora</option></select></label></div><p className="field-help">Termin vrijedi tek nakon potvrde Vespere.</p></fieldset>
          <div className="field-grid"><label><span>Ime i prezime</span><input type="text" name="name" autoComplete="name" required /></label><label><span>Telefon</span><input type="tel" name="phone" autoComplete="tel" required /></label></div>
          <label><span>E-mail, nije obavezno</span><input type="email" name="email" autoComplete="email" /></label>
          <label><span>Što želite promijeniti u prostoru?</span><textarea name="message" rows={4} placeholder="Npr. treba mi više radne plohe i lakši pristup posuđu." /></label>
          <label className="file-field"><ImagePlus aria-hidden="true" /><span><strong>Dodajte fotografije ili skicu</strong><small>JPG, PNG ili PDF u stvarnoj verziji</small></span><input type="file" multiple accept="image/*,.pdf" /></label>
          <button className="button button-accent form-submit" type="submit"><Send aria-hidden="true" /> Pripremite zahtjev za termin</button>
        </>}
      </form>
    </div></section>

    <section className="section container"><div className="kitchen-clarity"><div><p className="eyebrow">Bez nejasnih obećanja</p><h2>Što znači “po mjeri”?</h2><p>Mogućnosti ovise o odabranom kuhinjskom sustavu. Na ponudi treba jasno pisati koji su elementi standardni, što se konfigurira i gdje je moguća posebna prilagodba.</p></div><div className="clarity-list"><p><strong>Moduli</strong><span>Dostupne širine i rasporedi elemenata</span></p><p><strong>Materijali</strong><span>Fronte, korpusi, radne ploče i okovi</span></p><p><strong>Prilagodbe</strong><span>Završne stranice, ispune, visine i radna ploča</span></p><p><strong>Usluga</strong><span>Mjerenje, planiranje, dostava i montaža</span></p></div></div><Link className="text-link back-link" href="/"><ArrowLeft aria-hidden="true" /> Natrag na početnu</Link></section>
  </main></PageShell>;
}
